import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";
import SideBar from "./sidebar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <div className="flex flex-1 max-w-7xl mx-auto w-full px-4 py-6 space-x-6">
            <SideBar />
            <main className="flex-1 bg-white p-6 rounded-2xl shadow-md">
              {children}
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
