import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,player,nowplaying,main,sidebar
}: Readonly<{
  children: React.ReactNode;
  player: React.ReactNode;
  nowplaying: React.ReactNode
  main: React.ReactNode;
  sidebar: React.ReactNode
}>) {
  return (
    <html>
      <body className="grid grid-cols-[250px_1fr_300px] grid-rows-[1fr_auto] h-screen">
        {/* Top row: sidebar, main, nowplaying */}
        <div className="row-span-1 col-span-1 border-r">{sidebar}</div>
        <div className="row-span-1 col-span-1 overflow-y-auto">{main}</div>
        <div className="row-span-1 col-span-1 border-l">{nowplaying}</div>

        {/* Bottom row: player across all columns */}
        <div className="col-span-3 border-t">{player}</div>
      </body>
    </html>
  );
}
